### ISSUE TITLE
Refactor PlayerAvatar

### ISSUE THREAD

**Issue by Dammic** [Dammic/SecretSzanta#168]
Instead of passing all data about the user to it, the component itself should try to find the required data by using just userName.
Additionally, add options to hide all elements of the avatar, so:
        hideFascistAvatar: PropTypes.bool,
        hideDead: PropTypes.bool,
        hideWaitedFor: PropTypes.bool,
        hideOwner: PropTypes.bool,

This will cause a few other components to be smaller, as they will no longer have to get this data from tree only to show an avatar

**Comment by Terverok** [comment]
Not relevant anymore
